#debug: true
spring:
  application:
    name: ws-userinfo
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

Jwt:
  url: "/jwt/token"
  keyPair:
    privateExponent: 123
    modulus: 123

